/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package order_GUI;

import Database.OrderConnector;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class OrderList extends javax.swing.JInternalFrame {

    private String welcomeName;
    private String userRole;

    
    public OrderList(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        
        initComponents();
        loadTable();
    }
    
    public void loadTable() {
        DefaultTableModel orderModel = (DefaultTableModel) orderTable.getModel();
        
        orderModel.setRowCount(0);
        
        OrderConnector odrConn = new OrderConnector();
        
        List<Object[]> orders = odrConn.orderList();
        
        for(Object[] order : orders) {
            orderModel.addRow(order);
        }
    }
    
    private void searchOrdersTable() {

        String search = searchField.getText().trim();

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();

        model.setRowCount(0);

        OrderConnector ordConn = new OrderConnector();

        List<Object[]> orders = ordConn.searchOrder(search);

        for (Object[] order : orders) {
            model.addRow(order);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        displayAll = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 50));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "First Name", "Last Name", "Service", "Size", "Unit Price", "Quantity", "Total", "Order Status", "Payment Status"
            }
        ));
        jScrollPane1.setViewportView(orderTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1230, 610));

        searchButton.setBackground(new java.awt.Color(0, 153, 153));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 170, 50));

        displayAll.setBackground(new java.awt.Color(0, 153, 153));
        displayAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayAll.setForeground(new java.awt.Color(255, 255, 255));
        displayAll.setText("Display All");
        displayAll.addActionListener(this::displayAllActionPerformed);
        jPanel1.add(displayAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllActionPerformed
        loadTable();
    }//GEN-LAST:event_displayAllActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchOrdersTable();
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayAll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
