/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.DBConnection;
import Database.CustomerDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ArchivedCustomerFrame extends javax.swing.JFrame {
    private String userRole;
    private String welcomeName;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ArchivedCustomerFrame.class.getName());

    public ArchivedCustomerFrame(String welcomeName, String userRole) {
        this.userRole = userRole;
        this.welcomeName = welcomeName;
        
        initComponents();
        frameComponents();
        dashboardComponents();
        loadArchivedCustomers();
    }
    
    public void dashboardComponents() {
        setLocationRelativeTo(null);
    }
    
    public void frameComponents() {
        setLocationRelativeTo(null);
        setResizable(false);
        setAlwaysOnTop(true); 
    }
    
    private void searchCustomers() {
        String search = searchField.getText().trim();
        
        if(search.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please enter an customer information.","Search",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        CustomerDAO ctmDAO = new CustomerDAO();
        
        List<Object[]> customers = ctmDAO.searchArchivedCustomer(search);
        
        DefaultTableModel customerModel = (DefaultTableModel) customerTable.getModel();
        
        customerModel.setRowCount(0);
        
        for(Object[] row : customers) {
            customerModel.addRow(row);
        }
        
        if(customers.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Customer not found.","Search",JOptionPane.WARNING_MESSAGE);
            return;
        }
    }
    
    public void loadArchivedCustomers() {
        CustomerDAO ctmDAO = new CustomerDAO();
        
        List<Object[]> customers = ctmDAO.loadarchivedCustomer();
        
        DefaultTableModel customerModel = (DefaultTableModel) customerTable.getModel();
        
        customerModel.setRowCount(0);
        
        for(Object [] row : customers) {
            customerModel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        archiveButton = new javax.swing.JButton();
        displayAll = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Search: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchField.addActionListener(this::searchFieldActionPerformed);
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 310, 50));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Contact Number", "Email Address", "Customer Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1240, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        archiveButton.setBackground(new java.awt.Color(255, 255, 255));
        archiveButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        archiveButton.setForeground(new java.awt.Color(0, 0, 0));
        archiveButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\left-curved-arrow-7982_32.png")); // NOI18N
        archiveButton.setText("Retrieve");
        archiveButton.setIconTextGap(15);
        archiveButton.addActionListener(this::archiveButtonActionPerformed);
        jPanel1.add(archiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 160, 50));

        displayAll.setBackground(new java.awt.Color(255, 255, 255));
        displayAll.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        displayAll.setForeground(new java.awt.Color(0, 0, 0));
        displayAll.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\client-5251_32.png")); // NOI18N
        displayAll.setText("Display All");
        displayAll.setIconTextGap(15);
        displayAll.addActionListener(this::displayAllActionPerformed);
        jPanel1.add(displayAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 160, 50));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\search-2904_32.png")); // NOI18N
        searchButton.setText("Search");
        searchButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchButton.setIconTextGap(15);
        searchButton.addActionListener(this::searchButtonActionPerformed);
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 160, 50));

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\left-arrow-7304_32.png")); // NOI18N
        backButton.setText("Back");
        backButton.setIconTextGap(15);
        backButton.addActionListener(this::backButtonActionPerformed);
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchCustomers();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CustomerSearch ctmSearch = new CustomerSearch(welcomeName,userRole);
        ctmSearch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void displayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllActionPerformed
        searchField.setText("");
        loadArchivedCustomers();
    }//GEN-LAST:event_displayAllActionPerformed

    private void archiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveButtonActionPerformed
int selectedRow = customerTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Please select a customer to retrieve.",
                "No Customer Selected",
            JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        String customerID = customerTable.getValueAt(selectedRow,0).toString();
        
        int convertedCustomerID = Integer.parseInt(customerID.replace("CUST-", ""));

        String firstName = customerTable.getValueAt(selectedRow, 1).toString();

        String lastName = customerTable.getValueAt(selectedRow, 2).toString();

        int confirmation = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to retrieve "
            + firstName + " " + lastName + "?",
            "Retrieve Customer",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if(confirmation == JOptionPane.YES_OPTION) {
            
            CustomerDAO cmtDAO = new CustomerDAO();
            
            boolean retrieved = cmtDAO.retrieveCustomer(convertedCustomerID);
            
            if(retrieved) {
                JOptionPane.showMessageDialog(this,firstName + " has been retrieved successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
                loadArchivedCustomers();
            }
            else {
                JOptionPane.showMessageDialog(this,"Error in retrieving customer.","Database error",JOptionPane.ERROR_MESSAGE);
                return;
            }
        } 
    }//GEN-LAST:event_archiveButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        
    }//GEN-LAST:event_searchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archiveButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton displayAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
