/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Database.DBConnection;
import Database.CustomerDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerSearch extends javax.swing.JFrame {
    private String welcomeName;
    private String userRole;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerSearch.class.getName());

    public CustomerSearch(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        
        initComponents();
        frameComponents();
        dashboardComponents();
        loadCustomers();
    }
    
    public void dashboardComponents() {
        if(!userRole.equals("Administrator")) {
            viewArchive.setEnabled(false);
            archiveButton.setEnabled(false);
        }
    }
    
    public void frameComponents() {
        setLocationRelativeTo(null);
        setResizable(false);
        setAlwaysOnTop(true); 
    }
    
    private void searchCustomers() {
        
        String search = searchField.getText().trim();
        
        if(search.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please enter an customer information.","Search",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        CustomerDAO ctmDAO = new CustomerDAO();
        
        List<Object[]> customers = ctmDAO.searchCustomer(search);
        
        DefaultTableModel customerModel = (DefaultTableModel) customerTable.getModel();
        
        customerModel.setRowCount(0);
        
        for(Object[] row : customers) {
            customerModel.addRow(row);
        }
        
        if(customers.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Customer not found.","Search",JOptionPane.WARNING_MESSAGE);
            return;
        }
}
    
    private void loadCustomers() {
       CustomerDAO ctmDAO = new CustomerDAO();
       
       List<Object[]> customers = ctmDAO.loadCustomers();
       
       DefaultTableModel customerModel = (DefaultTableModel) customerTable.getModel();
       
       customerModel.setRowCount(0);
       
       for(Object[] row : customers) {
           customerModel.addRow(row);
       }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        displayAll = new javax.swing.JButton();
        archiveButton = new javax.swing.JButton();
        viewArchive = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 49));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 16, 470, 40));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\search-2904_32.png")); // NOI18N
        searchButton.setText("Search");
        searchButton.setIconTextGap(15);
        searchButton.addActionListener(this::searchButtonActionPerformed);
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 180, 50));

        displayAll.setBackground(new java.awt.Color(255, 255, 255));
        displayAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayAll.setForeground(new java.awt.Color(0, 0, 0));
        displayAll.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\client-5251_32.png")); // NOI18N
        displayAll.setText("Display All");
        displayAll.setIconTextGap(15);
        displayAll.addActionListener(this::displayAllActionPerformed);
        getContentPane().add(displayAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 190, 50));

        archiveButton.setBackground(new java.awt.Color(255, 255, 255));
        archiveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        archiveButton.setForeground(new java.awt.Color(0, 0, 0));
        archiveButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\remove-folder-11486_32.png")); // NOI18N
        archiveButton.setText("Archive");
        archiveButton.setIconTextGap(15);
        archiveButton.addActionListener(this::archiveButtonActionPerformed);
        getContentPane().add(archiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 180, 50));

        viewArchive.setBackground(new java.awt.Color(255, 255, 255));
        viewArchive.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewArchive.setForeground(new java.awt.Color(0, 0, 0));
        viewArchive.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\eye-12109_32.png")); // NOI18N
        viewArchive.setText("View Archive");
        viewArchive.setIconTextGap(5);
        viewArchive.addActionListener(this::viewArchiveActionPerformed);
        getContentPane().add(viewArchive, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, 50));

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\left-arrow-7304_32.png")); // NOI18N
        backButton.setText("Back");
        backButton.setIconTextGap(15);
        backButton.addActionListener(this::backButtonActionPerformed);
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, 170, 50));

        customerTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Contact Number", "Email Address", "Customer Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1540, 782));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\DASHBOARD BACKGROUNDS UPDATED.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchCustomers();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.hide();
    }//GEN-LAST:event_backButtonActionPerformed

    private void displayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllActionPerformed
        searchField.setText("");
        loadCustomers();
    }//GEN-LAST:event_displayAllActionPerformed

    private void archiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveButtonActionPerformed
        int selectedRow = customerTable.getSelectedRow();
        
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this,"Please select a customer to archive.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String customerID = customerTable.getValueAt(selectedRow, 0).toString();
        
        int convertedCustomerID = Integer.parseInt(customerID.replace("CUST-", ""));
        
        String firstName = customerTable.getValueAt(selectedRow, 1).toString();
        
        String lastName = customerTable.getValueAt(selectedRow, 2).toString();
        
        int confirmation = JOptionPane.showConfirmDialog(this,"Are you sure you want to archive " + firstName + " " + lastName + "?","Archive confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        
        if(confirmation == JOptionPane.YES_OPTION) {
            
            CustomerDAO cmtDAO = new CustomerDAO();
            
            boolean archived = cmtDAO.archiveCustomer(convertedCustomerID);
            
            if(archived) {
                JOptionPane.showMessageDialog(this,firstName + " has been archived successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
                loadCustomers();
            }
            else {
                JOptionPane.showMessageDialog(this,"Error in archiving customer.","Database error",JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_archiveButtonActionPerformed

    private void viewArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewArchiveActionPerformed
        ArchivedCustomer arcCustomer = new ArchivedCustomer(welcomeName,userRole);
        arcCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewArchiveActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archiveButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton displayAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton viewArchive;
    // End of variables declaration//GEN-END:variables
}
