/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Database.OrderConnector;
import Database.PaymentConnector;
import Utility.Order;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ReportsFrame extends javax.swing.JInternalFrame {
    private javax.swing.Timer clockTimer;
    private int currentOrderID = -1;
    private String welcomeName;
    private String userRole;

    
    public ReportsFrame(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        
        initComponents();
        displayDateTime();
        loadOverallStats();
        clockTimer = new javax.swing.Timer(1000, e -> displayDateTime());
        clockTimer.start();
    }
    
    public void displayDateTime() {
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MMMM dd, yyyy");
        
        LocalDate currentDate = LocalDate.now();
        
        dateLabel.setText(currentDate.format(dateFormatter));
        
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("hh:mm:ss a");
        
        LocalTime currentTime = LocalTime.now();
        
        timeLabel.setText(currentTime.format(timeFormatter));
    }
    
    
    private void loadDailySalesReport() {

        java.util.Date from = fromDate.getDate();
        java.util.Date to = toDate.getDate();

        if (from == null || to == null) {
            JOptionPane.showMessageDialog(this,"Please select both From and To dates.","Missing Dates",JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate fromDate = from.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        LocalDate toDate = to.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        if (fromDate.isAfter(toDate)) {
            JOptionPane.showMessageDialog(this,"The From date cannot be after the To date.","Invalid Date Range",JOptionPane.WARNING_MESSAGE);
            return;
        }

        OrderConnector connector = new OrderConnector();

        List<Object[]> sales = connector.getDailySalesReport(fromDate, toDate);

        DefaultTableModel model = (DefaultTableModel) salesTable.getModel();

        model.setRowCount(0);

        double totalSales = 0.00;

        for (Object[] row : sales) {
            model.addRow(row);
            totalSales += ((Number) row[2]).doubleValue();
        }

        generatedSalesLabel.setText(String.format("₱%,.2f", totalSales));
    }
    
    private void loadOverallStats() {

        OrderConnector connector = new OrderConnector();
        Object[] stats = connector.getOverallStats();
        
        revenueLabel.setText(
        String.format("₱%,.2f", ((Number) stats[0]).doubleValue()));

        overallOrdersLabel.setText(String.valueOf(stats[1]));

        overallCompletedLabel.setText(String.valueOf(stats[2]));
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fromDate = new com.toedter.calendar.JDateChooser();
        toDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        overallOrdersLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        revenueLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        overallCompletedLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        generatedSalesLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Reports");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fromDate.setBackground(new java.awt.Color(255, 255, 255));
        fromDate.setForeground(new java.awt.Color(0, 0, 0));
        fromDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 60));

        toDate.setBackground(new java.awt.Color(255, 255, 255));
        toDate.setForeground(new java.awt.Color(0, 0, 0));
        toDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 240, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("From");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("To");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 38));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overallOrdersLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        overallOrdersLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(overallOrdersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 350, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Overall Orders");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 360, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 500, 130));

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(salesTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 148, 629, 410));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generate Report");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 70, 200, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        revenueLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        revenueLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(revenueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 350, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Overall Revenue");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 350, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 148, 500, 130));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        overallCompletedLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        overallCompletedLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel8.add(overallCompletedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 350, 70));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Overall Completed");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 360, 30));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 432, 500, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        generatedSalesLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        generatedSalesLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(generatedSalesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 300, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 400, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1200, 580));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 153, 0));
        dateLabel.setText("jLabel15");
        jPanel1.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 200, 30));

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 153, 153));
        timeLabel.setText("jLabel16");
        jPanel1.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadDailySalesReport();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel generatedSalesLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel overallCompletedLabel;
    private javax.swing.JLabel overallOrdersLabel;
    private javax.swing.JLabel revenueLabel;
    private javax.swing.JTable salesTable;
    private javax.swing.JLabel timeLabel;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables
}
