/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Database.OrderConnector;
import Database.PaymentConnector;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TransactionHistory extends javax.swing.JInternalFrame {

    private String welcomeName;
    private String userRole;

    
    public TransactionHistory(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        
        initComponents();
        loadTransactionHistory();
    }
    
    private void displayAllTransactions() {

        PaymentConnector connector = new PaymentConnector();

        List<Object[]> transactions = connector.getTransactionHistory();

        DefaultTableModel model = (DefaultTableModel) transactionTable.getModel();

        model.setRowCount(0);

        for (Object[] transaction : transactions) {
            model.addRow(transaction);
        }
        searchField.setText("");
    }
    
    private void searchTransaction() {

        String search = searchField.getText().trim();

        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please enter a transaction ID, order ID, or customer name.","Empty Search",JOptionPane.WARNING_MESSAGE);
            return;
        }

        PaymentConnector connector = new PaymentConnector();

        List<Object[]> transactions = connector.searchTransaction(search);

        DefaultTableModel model = (DefaultTableModel) transactionTable.getModel();

        model.setRowCount(0);

        for (Object[] transaction : transactions) {
            model.addRow(transaction);
        }

        if (transactions.isEmpty()) {
            JOptionPane.showMessageDialog(this,"No matching transactions found.","Search Results",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void loadTransactionHistory() {

        DefaultTableModel model = (DefaultTableModel) transactionTable.getModel();

        model.setRowCount(0);

        PaymentConnector connector = new PaymentConnector();

        List<Object[]> transactions = connector.getTransactionHistory();

        for (Object[] transaction : transactions) {
            model.addRow(transaction);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        displayAll = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 50));

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Order ID", "First Name", "Last Name", "Service", "Size", "Quantity", "Total", "Order Date", "Payment Date"
            }
        ));
        jScrollPane1.setViewportView(transactionTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1230, 610));

        searchButton.setBackground(new java.awt.Color(0, 153, 153));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 170, 50));

        displayAll.setBackground(new java.awt.Color(0, 153, 153));
        displayAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayAll.setForeground(new java.awt.Color(255, 255, 255));
        displayAll.setText("Display All");
        displayAll.addActionListener(this::displayAllActionPerformed);
        jPanel1.add(displayAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllActionPerformed
        displayAllTransactions();
    }//GEN-LAST:event_displayAllActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchTransaction();
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayAll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
