/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Database.CustomerDAO;
import Database.ServiceDAO;
import Utility.DateSimulationHandler;
import Utility.FrameResizerRestriction;
import Utility.Service;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class UpdateServiceFrame extends javax.swing.JInternalFrame {
    private int servicesID;
    private String welcomeName;
    private String userRole;
    private javax.swing.Timer clockTimer;

    
    public UpdateServiceFrame(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        
        initComponents();
        displayDateTime();
        dashboardComponents();
        loadService();
    }
    
    
    public void dashboardComponents() {
        simulatedDate.setEditable(false);
        localTime.setEditable(false);
        categoryField.setEditable(false);
        unitField.setEditable(false);
        statusField.setEditable(false);
        
        clockTimer = new javax.swing.Timer(1000, e -> displayDateTime());
        clockTimer.start();
        
    }
    
    
     private void displayDateTime() {
        
        simulatedDate.setText(
        DateSimulationHandler.getDate().format(
            DateTimeFormatter.ofPattern("MMMM dd, yyyy")
            )
        );
        LocalTime currentTime = LocalTime.now();

        DateTimeFormatter timeFormatter =
        DateTimeFormatter.ofPattern("hh:mm:ss a");

    localTime.setText(currentTime.format(timeFormatter));
}
     public void loadService() {
        ServiceDAO svcDAO = new ServiceDAO();
         
        List<Object[]> services = svcDAO.loadServices();
        
        DefaultTableModel serviceModel = (DefaultTableModel) serviceTable.getModel();
        
        serviceModel.setRowCount(0);
        
        for(Object [] row : services) {
            serviceModel.addRow(row);
        }
     }
     
     public void searchService() {
         
         String search = searchField.getText().trim();
         
         if(search.isEmpty()) {
             JOptionPane.showMessageDialog(this,"Please enter an service option.","Seach",JOptionPane.WARNING_MESSAGE);
             loadService();
             return;
         }
         
         ServiceDAO svcDAO = new ServiceDAO();
         
         List<Object[]> services = svcDAO.searchService(search);
         
         DefaultTableModel serviceModel = (DefaultTableModel) serviceTable.getModel();
         
         serviceModel.setRowCount(0);
         
         for(Object [] row : services) {
             serviceModel.addRow(row);
         }
         
         if(services.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Service not found!","Invalid service",JOptionPane.WARNING_MESSAGE);
            return;
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        simulatedDate = new javax.swing.JTextField();
        localTime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        serviceNameField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        unitBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        statusBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        saveChangeButton = new javax.swing.JButton();
        searchIDField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        searchIDButton = new javax.swing.JButton();
        categoryField = new javax.swing.JTextField();
        unitField = new javax.swing.JTextField();
        statusField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simulatedDate.setBackground(new java.awt.Color(255, 255, 255));
        simulatedDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        simulatedDate.setForeground(new java.awt.Color(0, 153, 153));
        simulatedDate.setBorder(null);
        jPanel1.add(simulatedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 225, 50));

        localTime.setBackground(new java.awt.Color(255, 255, 255));
        localTime.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        localTime.setForeground(new java.awt.Color(255, 153, 0));
        localTime.setBorder(null);
        jPanel1.add(localTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 225, 50));

        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Service Name", "Category", "Unit", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(serviceTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 750, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\rgb-colors-10810_128.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Update Service");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 270, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Service Name: ");

        serviceNameField.setBackground(new java.awt.Color(255, 255, 255));
        serviceNameField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        serviceNameField.setForeground(new java.awt.Color(0, 0, 0));
        serviceNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        categoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(0, 0, 0));
        categoryLabel.setText("Category:");

        categoryBox.setBackground(new java.awt.Color(255, 255, 255));
        categoryBox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        categoryBox.setForeground(new java.awt.Color(0, 0, 0));
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select category...", "Printing", "Copying", "Scanning", "Photo", "Finishing" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Unit:");

        unitBox.setBackground(new java.awt.Color(255, 255, 255));
        unitBox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        unitBox.setForeground(new java.awt.Color(0, 0, 0));
        unitBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select unit type...", "Page", "Piece" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Price:");

        priceField.setBackground(new java.awt.Color(255, 255, 255));
        priceField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        priceField.setForeground(new java.awt.Color(0, 0, 0));

        statusBox.setBackground(new java.awt.Color(255, 255, 255));
        statusBox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        statusBox.setForeground(new java.awt.Color(0, 0, 0));
        statusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select status...", "Active", "Inactive" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Status:");

        clearButton.setBackground(new java.awt.Color(251, 51, 51));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        saveChangeButton.setBackground(new java.awt.Color(255, 153, 0));
        saveChangeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        saveChangeButton.setText("Save Changes");
        saveChangeButton.addActionListener(this::saveChangeButtonActionPerformed);

        searchIDField.setBackground(new java.awt.Color(255, 255, 255));
        searchIDField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        searchIDField.setForeground(new java.awt.Color(0, 0, 0));
        searchIDField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchIDField.addActionListener(this::searchIDFieldActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Search ID: ");

        searchIDButton.setBackground(new java.awt.Color(0, 153, 153));
        searchIDButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchIDButton.setForeground(new java.awt.Color(255, 255, 255));
        searchIDButton.setText("Search");
        searchIDButton.addActionListener(this::searchIDButtonActionPerformed);

        categoryField.setBackground(new java.awt.Color(255, 255, 255));
        categoryField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        unitField.setBackground(new java.awt.Color(255, 255, 255));
        unitField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        unitField.addActionListener(this::unitFieldActionPerformed);

        statusField.setBackground(new java.awt.Color(255, 255, 255));
        statusField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(saveChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(5, 5, 5)
                            .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unitField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unitBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(searchIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(categoryLabel))
                    .addComponent(categoryBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(categoryField))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(unitBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(unitField))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7))
                    .addComponent(statusBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(statusField))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 460, 530));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Search:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 90, 50));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.addActionListener(this::searchFieldActionPerformed);
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 260, 50));

        searchButton.setBackground(new java.awt.Color(0, 153, 153));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangeButtonActionPerformed
        String serviceName = serviceNameField.getText();
        String category = (String) categoryBox.getSelectedItem();
        String unit = (String) unitBox.getSelectedItem();
        String price = priceField.getText();
        String status = (String) statusBox.getSelectedItem();
        double convertedPrice;
        
        if(serviceName.isEmpty() && price.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Fields are required to be filled out.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(category.equals("Select category...")) {
            JOptionPane.showMessageDialog(this,"Please select a category.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(unit.equals("Select unit type...")) {
            JOptionPane.showMessageDialog(this,"Please select a unit type.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(price.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Price field is required to be filled out.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            convertedPrice = Double.parseDouble(price);
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(this,"Invalid price input!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(status.equals("Select status...")) {
            JOptionPane.showMessageDialog(this,"Please select status.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ServiceDAO svcDAO = new ServiceDAO();
        
        boolean updated = svcDAO.updateService(servicesID, serviceName, category, unit, convertedPrice, status);
        
        if(updated) {
            JOptionPane.showMessageDialog(this,"Successfully updated service!","Success!",JOptionPane.INFORMATION_MESSAGE);
            serviceNameField.setText("");
            categoryBox.setSelectedIndex(0);
            unitBox.setSelectedIndex(0);
            priceField.setText("");
            statusBox.setSelectedIndex(0);
            searchIDField.setText("");
            categoryField.setText("");
            unitField.setText("");
            statusField.setText("");
            loadService();
        } else {
            JOptionPane.showMessageDialog(this,"Error updating service","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_saveChangeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        serviceNameField.setText("");
        categoryBox.setSelectedIndex(0);
        unitBox.setSelectedIndex(0);
        priceField.setText("");
        statusBox.setSelectedIndex(0);
        searchIDField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchService();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIDFieldActionPerformed

    private void searchIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDButtonActionPerformed
        String serviceIDText = searchIDField.getText().trim();
        
        try {
            this.servicesID = Integer.parseInt(serviceIDText.replace("SVC-",""));
            
            ServiceDAO svcDAO = new ServiceDAO();
            
            Service svc = svcDAO.getService(servicesID);
            
            if(svc != null) {
                serviceNameField.setText(svc.getServiceName());
                categoryField.setText(svc.getServiceCategory());
                unitField.setText(svc.getServiceUnit());
                priceField.setText(String.valueOf(svc.getServicePrice()));
                statusField.setText(svc.getServiceStatus());
            } else {
                JOptionPane.showMessageDialog(this,"Service not found!","Not found!",JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(this,"Invalid service ID (SVC-XXX)","Invalid",JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_searchIDButtonActionPerformed

    private void unitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryBox;
    private javax.swing.JTextField categoryField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localTime;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton saveChangeButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton searchIDButton;
    private javax.swing.JTextField searchIDField;
    private javax.swing.JTextField serviceNameField;
    private javax.swing.JTable serviceTable;
    private javax.swing.JTextField simulatedDate;
    private javax.swing.JComboBox<String> statusBox;
    private javax.swing.JTextField statusField;
    private javax.swing.JComboBox<String> unitBox;
    private javax.swing.JTextField unitField;
    // End of variables declaration//GEN-END:variables
}
