/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package service_GUI;

import Database.CustomerConnector;
import Database.ServiceConnector;
import Utility.DateAndTimeHandler;
import Utility.FrameResizerRestriction;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ServiceFrame extends javax.swing.JInternalFrame {
    private String welcomeName;
    private String userRole;
    private javax.swing.Timer clockTimer;

    
    public ServiceFrame(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        
        initComponents();
        displayDateTime();
        dashboardComponents();
        loadService();
    }
    
    
    public void dashboardComponents() {
        
        localTime.setEditable(false);
        
        clockTimer = new javax.swing.Timer(1000, e -> displayDateTime());
        clockTimer.start();
        
    }
    
    
     private void displayDateTime() {
        
        simulatedDate.setText(DateAndTimeHandler.getDate().format(
            DateTimeFormatter.ofPattern("MMMM dd, yyyy")
            )
        );
        LocalTime currentTime = LocalTime.now();

        DateTimeFormatter timeFormatter =
        DateTimeFormatter.ofPattern("hh:mm:ss a");

    localTime.setText(currentTime.format(timeFormatter));
}
     public void loadService() {
        ServiceConnector svcDAO = new ServiceConnector();
         
        List<Object[]> services = svcDAO.loadServices();
        
        DefaultTableModel serviceModel = (DefaultTableModel) serviceTable.getModel();
        
        serviceModel.setRowCount(0);
        
        for(Object [] row : services) {
            serviceModel.addRow(row);
        }
     }
     
     public void searchService() {
         
         String search = searchField.getText().trim();
         
         if(search.isEmpty()) {
             JOptionPane.showMessageDialog(this,"Please enter an service option.","Seach",JOptionPane.WARNING_MESSAGE);
             loadService();
             return;
         }
         
         ServiceConnector svcDAO = new ServiceConnector();
         
         List<Object[]> services = svcDAO.searchService(search);
         
         DefaultTableModel serviceModel = (DefaultTableModel) serviceTable.getModel();
         
         serviceModel.setRowCount(0);
         
         for(Object [] row : services) {
             serviceModel.addRow(row);
         }
         
         if(services.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Service not found!","Invalid service",JOptionPane.WARNING_MESSAGE);
            return;
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        simulatedDate = new javax.swing.JTextField();
        localTime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        serviceNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        unitBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        statusBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        addServiceButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        sizeBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simulatedDate.setBackground(new java.awt.Color(255, 255, 255));
        simulatedDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        simulatedDate.setForeground(new java.awt.Color(0, 153, 153));
        simulatedDate.setBorder(null);
        jPanel1.add(simulatedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 225, 50));

        localTime.setBackground(new java.awt.Color(255, 255, 255));
        localTime.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        localTime.setForeground(new java.awt.Color(255, 153, 0));
        localTime.setBorder(null);
        jPanel1.add(localTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 225, 50));

        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Name", "Category", "Size", "Unit", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(serviceTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 750, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\rgb-colors-10810_128.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Add Service");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 270, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Service Name: ");

        serviceNameField.setBackground(new java.awt.Color(255, 255, 255));
        serviceNameField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        serviceNameField.setForeground(new java.awt.Color(0, 0, 0));
        serviceNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Category: ");

        categoryBox.setBackground(new java.awt.Color(255, 255, 255));
        categoryBox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        categoryBox.setForeground(new java.awt.Color(0, 0, 0));
        categoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select category...", "Printing", "Copying", "Scanning", "Photo", "Finishing" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Unit:");

        unitBox.setBackground(new java.awt.Color(255, 255, 255));
        unitBox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        unitBox.setForeground(new java.awt.Color(0, 0, 0));
        unitBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select unit type...", "Page", "Piece" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Price:");

        priceField.setBackground(new java.awt.Color(255, 255, 255));
        priceField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        priceField.setForeground(new java.awt.Color(0, 0, 0));

        statusBox.setBackground(new java.awt.Color(255, 255, 255));
        statusBox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        statusBox.setForeground(new java.awt.Color(0, 0, 0));
        statusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select status...", "Active", "Inactive" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Status:");

        clearButton.setBackground(new java.awt.Color(0, 153, 153));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        addServiceButton.setBackground(new java.awt.Color(255, 153, 0));
        addServiceButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        addServiceButton.setText("Add Service");
        addServiceButton.addActionListener(this::addServiceButtonActionPerformed);

        removeButton.setBackground(new java.awt.Color(255, 51, 51));
        removeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Remove ");

        sizeBox.setBackground(new java.awt.Color(255, 255, 255));
        sizeBox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        sizeBox.setForeground(new java.awt.Color(0, 0, 0));
        sizeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select size...", "A4", "A3", "Letter", "Legal", "A5", "A6", "1x1", "2x2", "3R", "4R", "5R", "8R" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Size:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unitBox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sizeBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 460, 530));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Search:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 90, 50));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.addActionListener(this::searchFieldActionPerformed);
        jPanel1.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 260, 50));

        searchButton.setBackground(new java.awt.Color(0, 153, 153));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServiceButtonActionPerformed
        String serviceName = serviceNameField.getText();
        String category = (String) categoryBox.getSelectedItem();
        String unit = (String) unitBox.getSelectedItem();
        String unitPrice = priceField.getText();
        String status = (String) statusBox.getSelectedItem();
        String size = (String) sizeBox.getSelectedItem();
        double convertedPrice;
        
        if(serviceName.isEmpty() && unitPrice.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Fields are requried to be filled out.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(category.equals("Select category...")) {
            JOptionPane.showMessageDialog(this,"Select a category.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(unit.equals("Select unit type...")) {
            JOptionPane.showMessageDialog(this,"Select a unit type.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(unitPrice.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Unit price is required to be filled out.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            convertedPrice = Double.parseDouble(unitPrice);
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(this,"Invalid price input!","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(status.equals("Select status...")) {
            JOptionPane.showMessageDialog(this,"Select status.","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        ServiceConnector svcDAO = new ServiceConnector();
            
        String serviceID = svcDAO.addService(serviceName,category,size,unit,convertedPrice,status);
            
        if(serviceID != null) {
            JOptionPane.showMessageDialog(this,"Service added successfully!","Success!",JOptionPane.INFORMATION_MESSAGE);
            serviceNameField.setText("");
            categoryBox.setSelectedIndex(0);
            unitBox.setSelectedIndex(0);
            priceField.setText("");
            statusBox.setSelectedIndex(0);
            loadService();
        }
        else {
            JOptionPane.showMessageDialog(this,"Adding service failure.","Database error",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_addServiceButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        serviceNameField.setText("");
        categoryBox.setSelectedIndex(0);
        unitBox.setSelectedIndex(0);
        priceField.setText("");
        statusBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchService();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        
    }//GEN-LAST:event_searchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServiceButton;
    private javax.swing.JComboBox<String> categoryBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localTime;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField serviceNameField;
    private javax.swing.JTable serviceTable;
    private javax.swing.JTextField simulatedDate;
    private javax.swing.JComboBox<String> sizeBox;
    private javax.swing.JComboBox<String> statusBox;
    private javax.swing.JComboBox<String> unitBox;
    // End of variables declaration//GEN-END:variables
}
