/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package printingservicemanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AdminAuthenticator extends javax.swing.JFrame {
    private String userRole;
    private String welcomeName;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminAuthenticator.class.getName());

    /**
     * Creates new form AdminAuthenticator
     */
    public AdminAuthenticator(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        passCode = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        verifyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showPin = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passCode.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        passCode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(passCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 450, 60));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("BACK");
        backButton.addActionListener(this::backButtonActionPerformed);
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 790, 180, 60));

        verifyButton.setBackground(new java.awt.Color(255, 255, 255));
        verifyButton.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        verifyButton.setForeground(new java.awt.Color(0, 0, 0));
        verifyButton.setText("VERIFY");
        verifyButton.addActionListener(this::verifyButtonActionPerformed);
        getContentPane().add(verifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 190, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN AUTHENTICATOR");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 560, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\user-security-11932_128.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 120, 130));

        showPin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        showPin.setForeground(new java.awt.Color(0, 0, 0));
        showPin.setText("SHOW PIN");
        showPin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        showPin.addActionListener(this::showPinActionPerformed);
        getContentPane().add(showPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\NEW NEW MAIN MAIN.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        String passField = new String(passCode.getPassword());
        
        if(passField.equals("127995121653")) {
            Dashboard newDashboard = new Dashboard(welcomeName,userRole);
            newDashboard.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Login backLogin = new Login();
        backLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void showPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPinActionPerformed
        if(showPin.isSelected()) {
            passCode.setEchoChar((char)0);
        }
        else {
            passCode.setEchoChar('*');
        }
    }//GEN-LAST:event_showPinActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passCode;
    private javax.swing.JCheckBox showPin;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
