/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package printingservicemanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ArchivedCustomer extends javax.swing.JFrame {
    private String welcomeName;
    private String userRole;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ArchivedCustomer.class.getName());

    public ArchivedCustomer(String welcomeName, String userRole) {
        this.welcomeName = welcomeName;
        this.userRole = userRole;
        
        initComponents();
        frameComponents();
        loadCustomers();
        uneditableTable();
    }
    
    public void frameComponents() {
        setLocationRelativeTo(null);
        setResizable(false);
        setAlwaysOnTop(true);
    }
    
    private void uneditableTable() {

    DefaultTableModel model =
            (DefaultTableModel) customerTable.getModel();

    customerTable.setDefaultEditor(Object.class, null);
    
    customerTable.getColumnModel().getColumn(0).setMinWidth(0);
    customerTable.getColumnModel().getColumn(0).setMaxWidth(0);
    customerTable.getColumnModel().getColumn(0).setPreferredWidth(0);
}
    
    private void searchCustomers() {

    String search = searchField.getText().trim();

    if (search.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter a customer name.",
            "Search",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

     String sql = "SELECT ctm_id, ctm_ftName, ctm_ltName, "
               + "ctm_phNumber, ctm_emAddress, ctm_Type "
               + "FROM tbl_customers "
               + "WHERE ctm_archived = 1 "
               + "AND (ctm_ftName LIKE ? OR ctm_ltName LIKE ?)";

    try (Connection conn = DBConnection.connect();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        String keyword = "%" + search + "%";

        pstmt.setString(1, keyword);
        pstmt.setString(2, keyword);

        try (ResultSet rs = pstmt.executeQuery()) {

            DefaultTableModel model =
                    (DefaultTableModel) customerTable.getModel();

            model.setRowCount(0);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("ctm_ftName"),
                    rs.getString("ctm_ltName"),
                    rs.getString("ctm_phNumber"),
                    rs.getString("ctm_emAddress"),
                    rs.getString("ctm_Type")
                });
            }

            // No results
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(
                    this,
                    "No customer found.",
                    "Search",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error searching customers: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    private void loadCustomers() {

    String sql = "SELECT ctm_id, ctm_ftName, ctm_ltName, "
               + "ctm_phNumber, ctm_emAddress, ctm_Type "
               + "FROM tbl_customers "
               + "WHERE ctm_archived = 1";

    try (Connection conn = DBConnection.connect();
         PreparedStatement pstmt = conn.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery()) {

        DefaultTableModel model =
                (DefaultTableModel) customerTable.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            Object[] row = {
                rs.getInt("ctm_id"),
                rs.getString("ctm_ftName"),
                rs.getString("ctm_ltName"),
                rs.getString("ctm_phNumber"),
                rs.getString("ctm_emAddress"),
                rs.getString("ctm_Type")
            };

            model.addRow(row);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
            this,
            "Error loading customers: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        displayAll = new javax.swing.JButton();
        RetrieveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 49));

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 16, 460, 40));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 160, 50));

        displayAll.setBackground(new java.awt.Color(255, 255, 255));
        displayAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayAll.setForeground(new java.awt.Color(0, 0, 0));
        displayAll.setText("Display All");
        displayAll.addActionListener(this::displayAllActionPerformed);
        getContentPane().add(displayAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 160, 50));

        RetrieveButton.setBackground(new java.awt.Color(255, 255, 255));
        RetrieveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RetrieveButton.setForeground(new java.awt.Color(0, 0, 0));
        RetrieveButton.setText("Retrieve");
        RetrieveButton.addActionListener(this::RetrieveButtonActionPerformed);
        getContentPane().add(RetrieveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 158, 50));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, 160, 50));

        customerTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Contact Number", "Email Address", "Customer Type"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1540, 782));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\DASHBOARD BACKGROUNDS UPDATED.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchCustomers();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CustomerSearch backSearch = new CustomerSearch(welcomeName,userRole);
        backSearch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void displayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllActionPerformed
        searchField.setText("");
        loadCustomers();
    }//GEN-LAST:event_displayAllActionPerformed

    private void RetrieveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrieveButtonActionPerformed
        int selectedRow = customerTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Please select a customer to retrieve.",
                "No Customer Selected",
            JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int customerID = Integer.parseInt(
            customerTable.getValueAt(selectedRow, 0).toString()
        );

        String firstName =
            customerTable.getValueAt(selectedRow, 1).toString();

        String lastName =
            customerTable.getValueAt(selectedRow, 2).toString();

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to retrieve "
            + firstName + " " + lastName + "?",
            "Retrieve Customer",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if(confirm == JOptionPane.YES_OPTION) {
            String sql = "UPDATE tbl_customers "
               + "SET ctm_archived = 0 "
               + "WHERE ctm_id = ?";

            try (Connection conn = DBConnection.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setInt(1, customerID);

                int updated = pstmt.executeUpdate();

                if (updated > 0) {

                    JOptionPane.showMessageDialog(
                    this,
                    "Customer retrieved successfully!"
                    );

                    loadCustomers();
                }
            
            
            } catch (SQLException e) {

                JOptionPane.showMessageDialog(
                this,
                "Error archiving customer: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
                );
            }
        } else if(confirm == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_RetrieveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RetrieveButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton displayAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
