/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package printingservicemanagement;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {
    private String welcomeName;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard(String welcomeName) {
        this.welcomeName = welcomeName;
        initComponents();
        welcomeMessage.setEditable(false);
        welcomeMessage.setText("Welcome, " + welcomeName + "!");
        
        if(!welcomeName.equals("admin")) {
            creationButton.setEnabled(false);
            reportsButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        welcomeMessage = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        customerButton = new javax.swing.JButton();
        serviceButton = new javax.swing.JButton();
        ordersButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        creationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("KiNN CDO PRINTING SERVICE MANAGEMENT SYSTEM");

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\exit-logout-2857_32.png")); // NOI18N
        logout.setText("LOGOUT");
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logout.setIconTextGap(8);
        logout.setMargin(new java.awt.Insets(2, 4, 2, 10));
        logout.addActionListener(this::logoutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1560, -1));

        welcomeMessage.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        welcomeMessage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        welcomeMessage.addActionListener(this::welcomeMessageActionPerformed);
        getContentPane().add(welcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 590, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        customerButton.setBackground(new java.awt.Color(153, 153, 153));
        customerButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerButton.setForeground(new java.awt.Color(0, 0, 0));
        customerButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\client-5251_128.png")); // NOI18N
        customerButton.setText("CUSTOMERS");
        customerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customerButton.addActionListener(this::customerButtonActionPerformed);

        serviceButton.setBackground(new java.awt.Color(153, 153, 153));
        serviceButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        serviceButton.setForeground(new java.awt.Color(0, 0, 0));
        serviceButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\consultation-services-team-black-26528_128.png")); // NOI18N
        serviceButton.setText("SERVICE");
        serviceButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serviceButton.addActionListener(this::serviceButtonActionPerformed);

        ordersButton.setBackground(new java.awt.Color(153, 153, 153));
        ordersButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ordersButton.setForeground(new java.awt.Color(0, 0, 0));
        ordersButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\list-6241_128.png")); // NOI18N
        ordersButton.setText("ORDERS");
        ordersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordersButton.addActionListener(this::ordersButtonActionPerformed);

        reportsButton.setBackground(new java.awt.Color(153, 153, 153));
        reportsButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(0, 0, 0));
        reportsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\tax-calculator-9256_128.png")); // NOI18N
        reportsButton.setText("REPORTS");
        reportsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        creationButton.setBackground(new java.awt.Color(153, 153, 153));
        creationButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        creationButton.setForeground(new java.awt.Color(0, 0, 0));
        creationButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\management-9642_128.png")); // NOI18N
        creationButton.setText("CREATION");
        creationButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        creationButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        creationButton.addActionListener(this::creationButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(customerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(serviceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1560, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\KINN CDO FRAME.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login newLogin = new Login();
        newLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void welcomeMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeMessageActionPerformed

    }//GEN-LAST:event_welcomeMessageActionPerformed

    private void creationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creationButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        Customer newCustomer = new Customer(welcomeName);
        newCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerButtonActionPerformed

    private void serviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceButtonActionPerformed
        Service newService = new Service(welcomeName);
        newService.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_serviceButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        OrdersSelection newSelection = new OrdersSelection(welcomeName);
        newSelection.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ordersButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creationButton;
    private javax.swing.JButton customerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton ordersButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JButton serviceButton;
    private javax.swing.JTextField welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
